{
    let num = 10;
    
    // calling the function inside block
    console.log(num)
}

// Calling a function outside
// block throws an Error
console.log(num)